package watogo

// Code generated by protoc-gen-go.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.4

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WebhookPayload represents the top-level structure of a WhatsApp webhook payload.
// This is the root object received in the HTTP POST body.
type WebhookPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The object type, typically "whatsapp_business_account".
	Object string `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// An array of entry objects. A webhook payload can contain multiple entries,
	// although usually it contains just one.
	Entry         []*Entry `protobuf:"bytes,2,rep,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookPayload) Reset() {
	*x = WebhookPayload{}
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookPayload) ProtoMessage() {}

func (x *WebhookPayload) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookPayload.ProtoReflect.Descriptor instead.
func (*WebhookPayload) Descriptor() ([]byte, []int) {
	return file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescGZIP(), []int{0}
}

func (x *WebhookPayload) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *WebhookPayload) GetEntry() []*Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// Entry represents a single entry in the webhook payload.
type Entry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the WhatsApp Business Account.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// An array of changes. This captures the specific events or updates
	// that triggered the webhook.
	Changes       []*Change `protobuf:"bytes,2,rep,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescGZIP(), []int{1}
}

func (x *Entry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entry) GetChanges() []*Change {
	if x != nil {
		return x.Changes
	}
	return nil
}

// Change represents a specific change event within an entry.
type Change struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The value object containing the details of the change.
	Value *Value `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Field describes the type of field that changed, e.g., "messages".
	// This helps identify which part of the account or message activity was updated.
	Field         string `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Change) Reset() {
	*x = Change{}
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change) ProtoMessage() {}

func (x *Change) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change.ProtoReflect.Descriptor instead.
func (*Change) Descriptor() ([]byte, []int) {
	return file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescGZIP(), []int{2}
}

func (x *Change) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Change) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

// Value contains the detailed data for a change event.
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The messaging product, typically "whatsapp".
	MessagingProduct string `protobuf:"bytes,1,opt,name=messaging_product,json=messagingProduct,proto3" json:"messaging_product,omitempty"`
	// Metadata about the business phone number that received the webhook.
	Metadata *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Array of contacts. Present in incoming messages.
	// Provides information about the user who sent the message.
	Contacts []*Contact `protobuf:"bytes,3,rep,name=contacts,proto3" json:"contacts,omitempty"`
	// Array of messages. Present in incoming messages.
	// Contains the actual message content and details.
	Messages []*Message `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
	// Array of statuses. Present in outgoing message status updates.
	// Examples: delivered, read, sent, failed.
	Statuses []*Status `protobuf:"bytes,5,rep,name=statuses,proto3" json:"statuses,omitempty"`
	// Array of errors. Present if the webhook notification contains an error.
	Errors        []*Error `protobuf:"bytes,6,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescGZIP(), []int{3}
}

func (x *Value) GetMessagingProduct() string {
	if x != nil {
		return x.MessagingProduct
	}
	return ""
}

func (x *Value) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Value) GetContacts() []*Contact {
	if x != nil {
		return x.Contacts
	}
	return nil
}

func (x *Value) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *Value) GetStatuses() []*Status {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *Value) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

// Error represents an error object received in the webhook.
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error code.
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Error code title.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Error code message.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Error code details.
	ErrorData *ErrorData `protobuf:"bytes,4,opt,name=error_data,json=errorData,proto3" json:"error_data,omitempty"`
	// Link to error code documentation.
	Href          string `protobuf:"bytes,5,opt,name=href,proto3" json:"href,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescGZIP(), []int{4}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetErrorData() *ErrorData {
	if x != nil {
		return x.ErrorData
	}
	return nil
}

func (x *Error) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

// ErrorData contains detailed information about the error.
type ErrorData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Detailed explanation of the error.
	Details       string `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorData) Reset() {
	*x = ErrorData{}
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorData) ProtoMessage() {}

func (x *ErrorData) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorData.ProtoReflect.Descriptor instead.
func (*ErrorData) Descriptor() ([]byte, []int) {
	return file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescGZIP(), []int{5}
}

func (x *ErrorData) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

// Metadata contains identification for the business phone number.
type Metadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The display phone number of the business.
	DisplayPhoneNumber string `protobuf:"bytes,1,opt,name=display_phone_number,json=displayPhoneNumber,proto3" json:"display_phone_number,omitempty"`
	// The ID of the phone number.
	PhoneNumberId string `protobuf:"bytes,2,opt,name=phone_number_id,json=phoneNumberId,proto3" json:"phone_number_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescGZIP(), []int{6}
}

func (x *Metadata) GetDisplayPhoneNumber() string {
	if x != nil {
		return x.DisplayPhoneNumber
	}
	return ""
}

func (x *Metadata) GetPhoneNumberId() string {
	if x != nil {
		return x.PhoneNumberId
	}
	return ""
}

// Contact represents a WhatsApp user.
type Contact struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Profile information of the user.
	Profile *Profile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	// The WhatsApp ID of the user (phone number).
	WaId string `protobuf:"bytes,2,opt,name=wa_id,json=waId,proto3" json:"wa_id,omitempty"`
	// Identity key hash.
	// POPULATION CONDITION: Only included if identity change check is enabled.
	// This allows you to verify if a user's identity key has changed.
	IdentityKeyHash string `protobuf:"bytes,3,opt,name=identity_key_hash,json=identityKeyHash,proto3" json:"identity_key_hash,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescGZIP(), []int{7}
}

func (x *Contact) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *Contact) GetWaId() string {
	if x != nil {
		return x.WaId
	}
	return ""
}

func (x *Contact) GetIdentityKeyHash() string {
	if x != nil {
		return x.IdentityKeyHash
	}
	return ""
}

// Profile contains the user's profile information.
type Profile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user's name as defined in their WhatsApp profile.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescGZIP(), []int{8}
}

func (x *Profile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Message represents a single message sent by a user to the business.
// Message represents a single message sent by a user to the business.
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The phone number of the sender.
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// The unique ID of the message assigned by WhatsApp.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// The timestamp when the WhatsApp server received the message from the user (Unix timestamp).
	Timestamp string `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The type of the message (e.g., "text", "image", "video", "audio").
	Type string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	// Content types - specific fields are populated based on the 'type'.
	Text  *Text  `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	Image *Image `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	Video *Video `protobuf:"bytes,7,opt,name=video,proto3" json:"video,omitempty"`
	Audio *Audio `protobuf:"bytes,8,opt,name=audio,proto3" json:"audio,omitempty"`
	// Context of the message.
	// POPULATION CONDITION: Populated in two main cases:
	// 1. If the message originated from a "Message business" button (contains referred_product).
	// 2. If the message was forwarded to the business by a user (contains forwarded flags).
	Context *Context `protobuf:"bytes,9,opt,name=context,proto3" json:"context,omitempty"`
	// Referral information.
	// POPULATION CONDITION: Only included if the message was sent via a Click to WhatsApp ad.
	Referral      *Referral `protobuf:"bytes,10,opt,name=referral,proto3" json:"referral,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescGZIP(), []int{9}
}

func (x *Message) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetText() *Text {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *Message) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *Message) GetVideo() *Video {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *Message) GetAudio() *Audio {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *Message) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *Message) GetReferral() *Referral {
	if x != nil {
		return x.Referral
	}
	return nil
}

// Text represents a text message payload.
type Text struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The body text of the message.
	Body          string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Text) Reset() {
	*x = Text{}
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescGZIP(), []int{10}
}

func (x *Text) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// Image represents an image message payload.
// Image represents an image message payload.
type Image struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Caption for the image, if provided by the user.
	Caption string `protobuf:"bytes,1,opt,name=caption,proto3" json:"caption,omitempty"`
	// The MIME type of the image (e.g., "image/jpeg", "image/png").
	MimeType string `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// The SHA-256 hash of the image file.
	Sha256 string `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// The unique ID of the image object. Can be used to retrieve the media binary.
	Id string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	// A direct URL to the image file. Note that this URL may expire or require auth headers.
	Url           string `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescGZIP(), []int{11}
}

func (x *Image) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *Image) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Image) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *Image) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Video represents a video message payload.
// Video represents a video message payload.
type Video struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Caption for the video, if provided by the user.
	Caption string `protobuf:"bytes,1,opt,name=caption,proto3" json:"caption,omitempty"`
	// The MIME type of the video (e.g., "video/mp4").
	MimeType string `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// The SHA-256 hash of the video file.
	Sha256 string `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// The unique ID of the video object. Can be used to retrieve the media binary.
	Id string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	// A direct URL to the video file. Note that this URL may expire or require auth headers.
	Url           string `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescGZIP(), []int{12}
}

func (x *Video) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *Video) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Video) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *Video) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Video) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Audio represents an audio message payload.
// Audio represents an audio message payload.
type Audio struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The MIME type of the audio file (e.g., "audio/ogg").
	MimeType string `protobuf:"bytes,1,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// The SHA-256 hash of the audio file.
	Sha256 string `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// The unique ID of the audio object. Can be used to retrieve the media binary.
	Id string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	// A direct URL to the audio file. Note that this URL may expire or require auth headers.
	Url string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	// Indicates if the audio is a voice message recorded by the user.
	// "true" if it is a voice note; "false" if it is a pre-recorded audio file.
	Voice         bool `protobuf:"varint,5,opt,name=voice,proto3" json:"voice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Audio) Reset() {
	*x = Audio{}
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Audio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Audio) ProtoMessage() {}

func (x *Audio) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Audio.ProtoReflect.Descriptor instead.
func (*Audio) Descriptor() ([]byte, []int) {
	return file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescGZIP(), []int{13}
}

func (x *Audio) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Audio) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *Audio) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Audio) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Audio) GetVoice() bool {
	if x != nil {
		return x.Voice
	}
	return false
}

// Context provides context for a message, such as if it was forwarded or replying to a product.
type Context struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The phone number of the sender of the context message (business number).
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// The ID of the message being replied to or referenced.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Product details if the message is in reference to a product from a catalog.
	ReferredProduct *ReferredProduct `protobuf:"bytes,3,opt,name=referred_product,json=referredProduct,proto3" json:"referred_product,omitempty"`
	// Indicates if the message was forwarded.
	// POPULATION CONDITION: Only included if the message was forwarded 5 times or less.
	Forwarded bool `protobuf:"varint,4,opt,name=forwarded,proto3" json:"forwarded,omitempty"`
	// Indicates if the message was frequently forwarded.
	// POPULATION CONDITION: Only included if the message was forwarded more than 5 times.
	FrequentlyForwarded bool `protobuf:"varint,5,opt,name=frequently_forwarded,json=frequentlyForwarded,proto3" json:"frequently_forwarded,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Context) Reset() {
	*x = Context{}
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescGZIP(), []int{14}
}

func (x *Context) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Context) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Context) GetReferredProduct() *ReferredProduct {
	if x != nil {
		return x.ReferredProduct
	}
	return nil
}

func (x *Context) GetForwarded() bool {
	if x != nil {
		return x.Forwarded
	}
	return false
}

func (x *Context) GetFrequentlyForwarded() bool {
	if x != nil {
		return x.FrequentlyForwarded
	}
	return false
}

// ReferredProduct contains details about a product being referenced in a message.
type ReferredProduct struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The catalog ID.
	CatalogId string `protobuf:"bytes,1,opt,name=catalog_id,json=catalogId,proto3" json:"catalog_id,omitempty"`
	// The product retailer ID.
	ProductRetailerId string `protobuf:"bytes,2,opt,name=product_retailer_id,json=productRetailerId,proto3" json:"product_retailer_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReferredProduct) Reset() {
	*x = ReferredProduct{}
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferredProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferredProduct) ProtoMessage() {}

func (x *ReferredProduct) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferredProduct.ProtoReflect.Descriptor instead.
func (*ReferredProduct) Descriptor() ([]byte, []int) {
	return file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescGZIP(), []int{15}
}

func (x *ReferredProduct) GetCatalogId() string {
	if x != nil {
		return x.CatalogId
	}
	return ""
}

func (x *ReferredProduct) GetProductRetailerId() string {
	if x != nil {
		return x.ProductRetailerId
	}
	return ""
}

// Referral contains information about the ad source that triggered the message.
// Referral contains information about the ad source that triggered the message.
type Referral struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The URL of the ad source that the user clicked.
	SourceUrl string `protobuf:"bytes,1,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	// The ID of the ad source (e.g., the specific Meta ad ID).
	SourceId string `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	// The type of source. Currently supported: "ad".
	SourceType string `protobuf:"bytes,3,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	// The body text of the ad that the user saw.
	Body string `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	// The headline of the ad that the user saw.
	Headline string `protobuf:"bytes,5,opt,name=headline,proto3" json:"headline,omitempty"`
	// The media type involved in the ad (e.g., "image", "video").
	MediaType string `protobuf:"bytes,6,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	// URL of the image used in the ad.
	ImageUrl string `protobuf:"bytes,7,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	// URL of the video used in the ad.
	VideoUrl string `protobuf:"bytes,8,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	// URL of the video thumbnail used in the ad.
	ThumbnailUrl string `protobuf:"bytes,9,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	// Click to WhatsApp (CTWA) Click ID.
	// POPULATION CONDITION: Omitted if message sent via a WhatsApp Status ad placement.
	// This identifier tracks the specific click on the ad.
	CtwaClid string `protobuf:"bytes,10,opt,name=ctwa_clid,json=ctwaClid,proto3" json:"ctwa_clid,omitempty"`
	// The welcome message configured for the ad that may be shown to the user.
	WelcomeMessage *WelcomeMessage `protobuf:"bytes,11,opt,name=welcome_message,json=welcomeMessage,proto3" json:"welcome_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Referral) Reset() {
	*x = Referral{}
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Referral) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Referral) ProtoMessage() {}

func (x *Referral) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Referral.ProtoReflect.Descriptor instead.
func (*Referral) Descriptor() ([]byte, []int) {
	return file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescGZIP(), []int{16}
}

func (x *Referral) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *Referral) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Referral) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *Referral) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Referral) GetHeadline() string {
	if x != nil {
		return x.Headline
	}
	return ""
}

func (x *Referral) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *Referral) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Referral) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *Referral) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *Referral) GetCtwaClid() string {
	if x != nil {
		return x.CtwaClid
	}
	return ""
}

func (x *Referral) GetWelcomeMessage() *WelcomeMessage {
	if x != nil {
		return x.WelcomeMessage
	}
	return nil
}

// WelcomeMessage holds the greeting text from an ad.
type WelcomeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WelcomeMessage) Reset() {
	*x = WelcomeMessage{}
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelcomeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeMessage) ProtoMessage() {}

func (x *WelcomeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeMessage.ProtoReflect.Descriptor instead.
func (*WelcomeMessage) Descriptor() ([]byte, []int) {
	return file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescGZIP(), []int{17}
}

func (x *WelcomeMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Status represents the status of an outgoing message.
type Status struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the message.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The status of the message (e.g., "delivered", "read", "sent", "failed").
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Timestamp of the status change.
	Timestamp string `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The WhatsApp ID of the recipient.
	RecipientId string `protobuf:"bytes,4,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	// Conversation details associated with this message status.
	Conversation *Conversation `protobuf:"bytes,5,opt,name=conversation,proto3" json:"conversation,omitempty"`
	// Pricing information for the message.
	Pricing       *Pricing `protobuf:"bytes,6,opt,name=pricing,proto3" json:"pricing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescGZIP(), []int{18}
}

func (x *Status) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Status) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Status) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Status) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *Status) GetConversation() *Conversation {
	if x != nil {
		return x.Conversation
	}
	return nil
}

func (x *Status) GetPricing() *Pricing {
	if x != nil {
		return x.Pricing
	}
	return nil
}

// Conversation represents the conversation context for pricing and billing.
type Conversation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the conversation.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The origin of the conversation.
	Origin        *Origin `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescGZIP(), []int{19}
}

func (x *Conversation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Conversation) GetOrigin() *Origin {
	if x != nil {
		return x.Origin
	}
	return nil
}

// Origin describes how the conversation started.
// Origin describes how the conversation started.
type Origin struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of origin indicating how the conversation was initiated.
	// Examples: "service" (user-initiated), "utility", "marketing", "authentication" (business-initiated).
	Type          string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Origin) Reset() {
	*x = Origin{}
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Origin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Origin) ProtoMessage() {}

func (x *Origin) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Origin.ProtoReflect.Descriptor instead.
func (*Origin) Descriptor() ([]byte, []int) {
	return file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescGZIP(), []int{20}
}

func (x *Origin) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// Pricing contains billable information about the message.
// Pricing contains billable information about the message.
type Pricing struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates if the message is billable.
	Billable bool `protobuf:"varint,1,opt,name=billable,proto3" json:"billable,omitempty"`
	// The pricing model used. Example: "CBP" (Conversational Business Pricing).
	PricingModel string `protobuf:"bytes,2,opt,name=pricing_model,json=pricingModel,proto3" json:"pricing_model,omitempty"`
	// The category of the conversation for pricing purposes.
	// Examples: "business_initiated", "user_initiated", "service", "utility", "marketing".
	Category      string `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pricing) Reset() {
	*x = Pricing{}
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pricing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pricing) ProtoMessage() {}

func (x *Pricing) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pricing.ProtoReflect.Descriptor instead.
func (*Pricing) Descriptor() ([]byte, []int) {
	return file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescGZIP(), []int{21}
}

func (x *Pricing) GetBillable() bool {
	if x != nil {
		return x.Billable
	}
	return false
}

func (x *Pricing) GetPricingModel() string {
	if x != nil {
		return x.PricingModel
	}
	return ""
}

func (x *Pricing) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

// VerificationRequest represents the parameters of a GET request used by Meta
// to verify a webhook endpoint.
type VerificationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The hub object containing verification details.
	Hub           *VerificationRequest_Hub `protobuf:"bytes,1,opt,name=hub,proto3" json:"hub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationRequest) Reset() {
	*x = VerificationRequest{}
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationRequest) ProtoMessage() {}

func (x *VerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationRequest.ProtoReflect.Descriptor instead.
func (*VerificationRequest) Descriptor() ([]byte, []int) {
	return file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescGZIP(), []int{22}
}

func (x *VerificationRequest) GetHub() *VerificationRequest_Hub {
	if x != nil {
		return x.Hub
	}
	return nil
}

type VerificationRequest_Hub struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// mode: The mode of the request. For verification, this should be "subscribe".
	Mode string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	// challenge: A random string generated by Meta that must be returned
	// as a plain text response if the request is valid (status 200).
	Challenge string `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	// verify_token: A verification string chosen by the business.
	// This must match the Verify Token configured in the App Dashboard.
	VerifyToken   string `protobuf:"bytes,3,opt,name=verify_token,json=verifyToken,proto3" json:"verify_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationRequest_Hub) Reset() {
	*x = VerificationRequest_Hub{}
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationRequest_Hub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationRequest_Hub) ProtoMessage() {}

func (x *VerificationRequest_Hub) ProtoReflect() protoreflect.Message {
	mi := &file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationRequest_Hub.ProtoReflect.Descriptor instead.
func (*VerificationRequest_Hub) Descriptor() ([]byte, []int) {
	return file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescGZIP(), []int{22, 0}
}

func (x *VerificationRequest_Hub) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *VerificationRequest_Hub) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

func (x *VerificationRequest_Hub) GetVerifyToken() string {
	if x != nil {
		return x.VerifyToken
	}
	return ""
}

var File_alis_ge_ruan_agent_v1_whatsapp_proto protoreflect.FileDescriptor

const file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDesc = "" +
	"\n" +
	"$alis/ge/ruan/agent/v1/whatsapp.proto\x12\x15alis.ge.ruan.agent.v1\"\\\n" +
	"\x0eWebhookPayload\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x122\n" +
	"\x05entry\x18\x02 \x03(\v2\x1c.alis.ge.ruan.agent.v1.EntryR\x05entry\"P\n" +
	"\x05Entry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\achanges\x18\x02 \x03(\v2\x1d.alis.ge.ruan.agent.v1.ChangeR\achanges\"R\n" +
	"\x06Change\x122\n" +
	"\x05value\x18\x01 \x01(\v2\x1c.alis.ge.ruan.agent.v1.ValueR\x05value\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\"\xda\x02\n" +
	"\x05Value\x12+\n" +
	"\x11messaging_product\x18\x01 \x01(\tR\x10messagingProduct\x12;\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1f.alis.ge.ruan.agent.v1.MetadataR\bmetadata\x12:\n" +
	"\bcontacts\x18\x03 \x03(\v2\x1e.alis.ge.ruan.agent.v1.ContactR\bcontacts\x12:\n" +
	"\bmessages\x18\x04 \x03(\v2\x1e.alis.ge.ruan.agent.v1.MessageR\bmessages\x129\n" +
	"\bstatuses\x18\x05 \x03(\v2\x1d.alis.ge.ruan.agent.v1.StatusR\bstatuses\x124\n" +
	"\x06errors\x18\x06 \x03(\v2\x1c.alis.ge.ruan.agent.v1.ErrorR\x06errors\"\xa0\x01\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12?\n" +
	"\n" +
	"error_data\x18\x04 \x01(\v2 .alis.ge.ruan.agent.v1.ErrorDataR\terrorData\x12\x12\n" +
	"\x04href\x18\x05 \x01(\tR\x04href\"%\n" +
	"\tErrorData\x12\x18\n" +
	"\adetails\x18\x01 \x01(\tR\adetails\"d\n" +
	"\bMetadata\x120\n" +
	"\x14display_phone_number\x18\x01 \x01(\tR\x12displayPhoneNumber\x12&\n" +
	"\x0fphone_number_id\x18\x02 \x01(\tR\rphoneNumberId\"\x84\x01\n" +
	"\aContact\x128\n" +
	"\aprofile\x18\x01 \x01(\v2\x1e.alis.ge.ruan.agent.v1.ProfileR\aprofile\x12\x13\n" +
	"\x05wa_id\x18\x02 \x01(\tR\x04waId\x12*\n" +
	"\x11identity_key_hash\x18\x03 \x01(\tR\x0fidentityKeyHash\"\x1d\n" +
	"\aProfile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xa3\x03\n" +
	"\aMessage\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12/\n" +
	"\x04text\x18\x05 \x01(\v2\x1b.alis.ge.ruan.agent.v1.TextR\x04text\x122\n" +
	"\x05image\x18\x06 \x01(\v2\x1c.alis.ge.ruan.agent.v1.ImageR\x05image\x122\n" +
	"\x05video\x18\a \x01(\v2\x1c.alis.ge.ruan.agent.v1.VideoR\x05video\x122\n" +
	"\x05audio\x18\b \x01(\v2\x1c.alis.ge.ruan.agent.v1.AudioR\x05audio\x128\n" +
	"\acontext\x18\t \x01(\v2\x1e.alis.ge.ruan.agent.v1.ContextR\acontext\x12;\n" +
	"\breferral\x18\n" +
	" \x01(\v2\x1f.alis.ge.ruan.agent.v1.ReferralR\breferral\"\x1a\n" +
	"\x04Text\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\"x\n" +
	"\x05Image\x12\x18\n" +
	"\acaption\x18\x01 \x01(\tR\acaption\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\"x\n" +
	"\x05Video\x12\x18\n" +
	"\acaption\x18\x01 \x01(\tR\acaption\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\"t\n" +
	"\x05Audio\x12\x1b\n" +
	"\tmime_type\x18\x01 \x01(\tR\bmimeType\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x14\n" +
	"\x05voice\x18\x05 \x01(\bR\x05voice\"\xd1\x01\n" +
	"\aContext\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12Q\n" +
	"\x10referred_product\x18\x03 \x01(\v2&.alis.ge.ruan.agent.v1.ReferredProductR\x0freferredProduct\x12\x1c\n" +
	"\tforwarded\x18\x04 \x01(\bR\tforwarded\x121\n" +
	"\x14frequently_forwarded\x18\x05 \x01(\bR\x13frequentlyForwarded\"`\n" +
	"\x0fReferredProduct\x12\x1d\n" +
	"\n" +
	"catalog_id\x18\x01 \x01(\tR\tcatalogId\x12.\n" +
	"\x13product_retailer_id\x18\x02 \x01(\tR\x11productRetailerId\"\x82\x03\n" +
	"\bReferral\x12\x1d\n" +
	"\n" +
	"source_url\x18\x01 \x01(\tR\tsourceUrl\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12\x1f\n" +
	"\vsource_type\x18\x03 \x01(\tR\n" +
	"sourceType\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x1a\n" +
	"\bheadline\x18\x05 \x01(\tR\bheadline\x12\x1d\n" +
	"\n" +
	"media_type\x18\x06 \x01(\tR\tmediaType\x12\x1b\n" +
	"\timage_url\x18\a \x01(\tR\bimageUrl\x12\x1b\n" +
	"\tvideo_url\x18\b \x01(\tR\bvideoUrl\x12#\n" +
	"\rthumbnail_url\x18\t \x01(\tR\fthumbnailUrl\x12\x1b\n" +
	"\tctwa_clid\x18\n" +
	" \x01(\tR\bctwaClid\x12N\n" +
	"\x0fwelcome_message\x18\v \x01(\v2%.alis.ge.ruan.agent.v1.WelcomeMessageR\x0ewelcomeMessage\"$\n" +
	"\x0eWelcomeMessage\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\xf4\x01\n" +
	"\x06Status\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12!\n" +
	"\frecipient_id\x18\x04 \x01(\tR\vrecipientId\x12G\n" +
	"\fconversation\x18\x05 \x01(\v2#.alis.ge.ruan.agent.v1.ConversationR\fconversation\x128\n" +
	"\apricing\x18\x06 \x01(\v2\x1e.alis.ge.ruan.agent.v1.PricingR\apricing\"U\n" +
	"\fConversation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x125\n" +
	"\x06origin\x18\x02 \x01(\v2\x1d.alis.ge.ruan.agent.v1.OriginR\x06origin\"\x1c\n" +
	"\x06Origin\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\"f\n" +
	"\aPricing\x12\x1a\n" +
	"\bbillable\x18\x01 \x01(\bR\bbillable\x12#\n" +
	"\rpricing_model\x18\x02 \x01(\tR\fpricingModel\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\"\xb3\x01\n" +
	"\x13VerificationRequest\x12@\n" +
	"\x03hub\x18\x01 \x01(\v2..alis.ge.ruan.agent.v1.VerificationRequest.HubR\x03hub\x1aZ\n" +
	"\x03Hub\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x1c\n" +
	"\tchallenge\x18\x02 \x01(\tR\tchallenge\x12!\n" +
	"\fverify_token\x18\x03 \x01(\tR\vverifyTokenB:Z8internal.ge.alis.services/protobuf/alis/ge/ruan/agent/v1b\x06proto3"

var (
	file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescOnce sync.Once
	file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescData []byte
)

func file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescGZIP() []byte {
	file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescOnce.Do(func() {
		file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDesc), len(file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDesc)))
	})
	return file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDescData
}

var file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_alis_ge_ruan_agent_v1_whatsapp_proto_goTypes = []any{
	(*WebhookPayload)(nil),          // 0: alis.ge.ruan.agent.v1.WebhookPayload
	(*Entry)(nil),                   // 1: alis.ge.ruan.agent.v1.Entry
	(*Change)(nil),                  // 2: alis.ge.ruan.agent.v1.Change
	(*Value)(nil),                   // 3: alis.ge.ruan.agent.v1.Value
	(*Error)(nil),                   // 4: alis.ge.ruan.agent.v1.Error
	(*ErrorData)(nil),               // 5: alis.ge.ruan.agent.v1.ErrorData
	(*Metadata)(nil),                // 6: alis.ge.ruan.agent.v1.Metadata
	(*Contact)(nil),                 // 7: alis.ge.ruan.agent.v1.Contact
	(*Profile)(nil),                 // 8: alis.ge.ruan.agent.v1.Profile
	(*Message)(nil),                 // 9: alis.ge.ruan.agent.v1.Message
	(*Text)(nil),                    // 10: alis.ge.ruan.agent.v1.Text
	(*Image)(nil),                   // 11: alis.ge.ruan.agent.v1.Image
	(*Video)(nil),                   // 12: alis.ge.ruan.agent.v1.Video
	(*Audio)(nil),                   // 13: alis.ge.ruan.agent.v1.Audio
	(*Context)(nil),                 // 14: alis.ge.ruan.agent.v1.Context
	(*ReferredProduct)(nil),         // 15: alis.ge.ruan.agent.v1.ReferredProduct
	(*Referral)(nil),                // 16: alis.ge.ruan.agent.v1.Referral
	(*WelcomeMessage)(nil),          // 17: alis.ge.ruan.agent.v1.WelcomeMessage
	(*Status)(nil),                  // 18: alis.ge.ruan.agent.v1.Status
	(*Conversation)(nil),            // 19: alis.ge.ruan.agent.v1.Conversation
	(*Origin)(nil),                  // 20: alis.ge.ruan.agent.v1.Origin
	(*Pricing)(nil),                 // 21: alis.ge.ruan.agent.v1.Pricing
	(*VerificationRequest)(nil),     // 22: alis.ge.ruan.agent.v1.VerificationRequest
	(*VerificationRequest_Hub)(nil), // 23: alis.ge.ruan.agent.v1.VerificationRequest.Hub
}
var file_alis_ge_ruan_agent_v1_whatsapp_proto_depIdxs = []int32{
	1,  // 0: alis.ge.ruan.agent.v1.WebhookPayload.entry:type_name -> alis.ge.ruan.agent.v1.Entry
	2,  // 1: alis.ge.ruan.agent.v1.Entry.changes:type_name -> alis.ge.ruan.agent.v1.Change
	3,  // 2: alis.ge.ruan.agent.v1.Change.value:type_name -> alis.ge.ruan.agent.v1.Value
	6,  // 3: alis.ge.ruan.agent.v1.Value.metadata:type_name -> alis.ge.ruan.agent.v1.Metadata
	7,  // 4: alis.ge.ruan.agent.v1.Value.contacts:type_name -> alis.ge.ruan.agent.v1.Contact
	9,  // 5: alis.ge.ruan.agent.v1.Value.messages:type_name -> alis.ge.ruan.agent.v1.Message
	18, // 6: alis.ge.ruan.agent.v1.Value.statuses:type_name -> alis.ge.ruan.agent.v1.Status
	4,  // 7: alis.ge.ruan.agent.v1.Value.errors:type_name -> alis.ge.ruan.agent.v1.Error
	5,  // 8: alis.ge.ruan.agent.v1.Error.error_data:type_name -> alis.ge.ruan.agent.v1.ErrorData
	8,  // 9: alis.ge.ruan.agent.v1.Contact.profile:type_name -> alis.ge.ruan.agent.v1.Profile
	10, // 10: alis.ge.ruan.agent.v1.Message.text:type_name -> alis.ge.ruan.agent.v1.Text
	11, // 11: alis.ge.ruan.agent.v1.Message.image:type_name -> alis.ge.ruan.agent.v1.Image
	12, // 12: alis.ge.ruan.agent.v1.Message.video:type_name -> alis.ge.ruan.agent.v1.Video
	13, // 13: alis.ge.ruan.agent.v1.Message.audio:type_name -> alis.ge.ruan.agent.v1.Audio
	14, // 14: alis.ge.ruan.agent.v1.Message.context:type_name -> alis.ge.ruan.agent.v1.Context
	16, // 15: alis.ge.ruan.agent.v1.Message.referral:type_name -> alis.ge.ruan.agent.v1.Referral
	15, // 16: alis.ge.ruan.agent.v1.Context.referred_product:type_name -> alis.ge.ruan.agent.v1.ReferredProduct
	17, // 17: alis.ge.ruan.agent.v1.Referral.welcome_message:type_name -> alis.ge.ruan.agent.v1.WelcomeMessage
	19, // 18: alis.ge.ruan.agent.v1.Status.conversation:type_name -> alis.ge.ruan.agent.v1.Conversation
	21, // 19: alis.ge.ruan.agent.v1.Status.pricing:type_name -> alis.ge.ruan.agent.v1.Pricing
	20, // 20: alis.ge.ruan.agent.v1.Conversation.origin:type_name -> alis.ge.ruan.agent.v1.Origin
	23, // 21: alis.ge.ruan.agent.v1.VerificationRequest.hub:type_name -> alis.ge.ruan.agent.v1.VerificationRequest.Hub
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_alis_ge_ruan_agent_v1_whatsapp_proto_init() }
func file_alis_ge_ruan_agent_v1_whatsapp_proto_init() {
	if File_alis_ge_ruan_agent_v1_whatsapp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDesc), len(file_alis_ge_ruan_agent_v1_whatsapp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alis_ge_ruan_agent_v1_whatsapp_proto_goTypes,
		DependencyIndexes: file_alis_ge_ruan_agent_v1_whatsapp_proto_depIdxs,
		MessageInfos:      file_alis_ge_ruan_agent_v1_whatsapp_proto_msgTypes,
	}.Build()
	File_alis_ge_ruan_agent_v1_whatsapp_proto = out.File
	file_alis_ge_ruan_agent_v1_whatsapp_proto_goTypes = nil
	file_alis_ge_ruan_agent_v1_whatsapp_proto_depIdxs = nil
}
